#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
诊断admin用户无法看到研发产品的问题

问题现象：admin用户在研发产品列表页面看不到任何数据，但数据库确认有12条记录

诊断时间：2025-11-09
"""
import sys, os

# 路径修正 - 支持从任何位置运行
def get_project_root():
    current = os.path.dirname(os.path.abspath(__file__))
    while current != '/':
        if os.path.exists(os.path.join(current, 'app')) and \
           os.path.exists(os.path.join(current, 'run.py')):
            return current
        current = os.path.dirname(current)
    raise RuntimeError("无法找到项目根目录")

sys.path.insert(0, get_project_root())

def main():
    print("=" * 80)
    print("🔍 研发产品可见性问题诊断报告")
    print("=" * 80)
    print()
    
    print("📋 问题描述：")
    print("  - admin用户在研发产品列表页面看不到任何数据")
    print("  - 数据库中确认有12条dev_products记录")
    print("  - 路由代码使用get_viewable_data(DevProduct, current_user)进行权限过滤")
    print()
    
    print("=" * 80)
    print("🔎 根因分析")
    print("=" * 80)
    print()
    
    print("1️⃣ 权限配置问题")
    print("   ❌ admin用户的product模块权限配置错误")
    print()
    print("   数据库记录：")
    print("   SELECT * FROM permissions WHERE user_id=5 AND module='product';")
    print("   ┌────┬─────────┬──────────┬──────────┬────────────┬──────────────────┐")
    print("   │ id │ user_id │ can_view │ can_edit │ can_delete │ permission_level │")
    print("   ├────┼─────────┼──────────┼──────────┼────────────┼──────────────────┤")
    print("   │ 73 │ 5       │ true     │ true     │ true       │ personal         │")
    print("   └────┴─────────┴──────────┴──────────┴────────────┴──────────────────┘")
    print()
    print("   ⚠️  关键问题：permission_level = 'personal'")
    print()
    
    print("2️⃣ 权限处理流程")
    print()
    print("   步骤1：路由调用 get_viewable_data(DevProduct, current_user)")
    print("   文件：app/routes/dev_product_management.py:37")
    print()
    print("   步骤2：access_control.py 检查用户角色")
    print("   文件：app/utils/access_control.py:342-348")
    print("   代码：")
    print("   ```python")
    print("   if user.role == 'admin':")
    print("       # 管理员可以查看所有数据")
    print("       return model_class.query.filter(*special_filters)")
    print("   ```")
    print("   ✅ admin用户通过role检查，应该返回所有数据")
    print()
    print("   ⚠️  但是！接下来进入DevProduct特殊处理...")
    print()
    print("   步骤3：DevProduct模型特殊处理")
    print("   文件：app/utils/access_control.py:459-509")
    print("   代码：")
    print("   ```python")
    print("   if model_class.__name__ == 'DevProduct':")
    print("       if not user.has_permission('product', 'view'):")
    print("           return model_class.query.filter(False)")
    print("       ")
    print("       permission_level = user.get_permission_level('product')")
    print("       # 根据permission_level进行过滤...")
    print("   ```")
    print()
    print("   步骤4：user.get_permission_level('product') 返回什么？")
    print("   文件：app/models/user.py:190-253")
    print("   代码：")
    print("   ```python")
    print("   def get_permission_level(self, module):")
    print("       # 管理员默认拥有系统级权限")
    print("       if self.role == 'admin':")
    print("           return 'system'  # ✅ 应该返回这个")
    print("       ")
    print("       # ... 其他逻辑 ...")
    print("       ")
    print("       # 如果有个人权限记录且permission_level不为None")
    print("       if permission and permission.permission_level is not None:")
    print("           final_level = permission.permission_level  # ❌ 返回'personal'")
    print("       else:")
    print("           final_level = role_level")
    print("   ```")
    print()
    print("   ❌ 问题：代码在207-209行已经检查了admin角色应返回'system'")
    print("   ❌ 但是：240行的逻辑覆盖了admin的判断！")
    print()
    
    print("3️⃣ 执行流程分析")
    print()
    print("   实际执行路径：")
    print("   ┌─────────────────────────────────────────────────────────────┐")
    print("   │ 1. get_viewable_data(DevProduct, admin_user)                │")
    print("   │    ↓                                                        │")
    print("   │ 2. 检查 user.role == 'admin' ✅                            │")
    print("   │    → 本应返回所有数据                                      │")
    print("   │    ↓                                                        │")
    print("   │ 3. 但进入DevProduct特殊处理（line 459）                    │")
    print("   │    ↓                                                        │")
    print("   │ 4. 调用 user.get_permission_level('product')               │")
    print("   │    ↓                                                        │")
    print("   │ 5. get_permission_level()中：                              │")
    print("   │    - Line 208: if self.role == 'admin': ✅                 │")
    print("   │    - Line 209: return 'system' ← 应该到此结束             │")
    print("   │    ↓                                                        │")
    print("   │ 6. ❌ 但实际没有执行到！                                   │")
    print("   │    因为有个人权限记录：permission_level='personal'        │")
    print("   │    Line 240覆盖了admin的判断                              │")
    print("   │    ↓                                                        │")
    print("   │ 7. 返回 'personal' 给DevProduct过滤逻辑                   │")
    print("   │    ↓                                                        │")
    print("   │ 8. 执行personal级别过滤（line 486-504）                   │")
    print("   │    ↓                                                        │")
    print("   │ 9. 调用 get_personal_viewable_user_ids(admin)             │")
    print("   │    → 返回：[5] （只有admin自己）                          │")
    print("   │    ↓                                                        │")
    print("   │ 10. 查询条件：owner_id IN (5)                             │")
    print("   │     → 只能看到10条记录（owner_id=5的记录）                │")
    print("   │     → 看不到2条owner_id=10的记录                          │")
    print("   └─────────────────────────────────────────────────────────────┘")
    print()
    
    print("4️⃣ 代码逻辑冲突")
    print()
    print("   ⚠️  access_control.py 存在两层admin检查：")
    print()
    print("   第一层（Line 342-348）：")
    print("   ```python")
    print("   if user.role == 'admin':")
    print("       return model_class.query.filter(*special_filters)  # 返回所有数据")
    print("   ```")
    print("   ✅ 这层检查对大多数模型有效")
    print()
    print("   第二层（Line 459-509）：")
    print("   ```python")
    print("   if model_class.__name__ == 'DevProduct':")
    print("       permission_level = user.get_permission_level('product')")
    print("       # 根据permission_level过滤...")
    print("   ```")
    print("   ❌ DevProduct特殊处理绕过了第一层admin检查")
    print("   ❌ 依赖get_permission_level()的返回值")
    print("   ❌ get_permission_level()被个人权限记录覆盖")
    print()
    
    print("=" * 80)
    print("💡 修复方案")
    print("=" * 80)
    print()
    
    print("方案1：删除错误的个人权限记录（推荐）")
    print("   SQL:")
    print("   ```sql")
    print("   DELETE FROM permissions WHERE user_id = 5 AND module = 'product';")
    print("   ```")
    print()
    print("   理由：")
    print("   - admin用户应该完全依赖角色权限，不需要个人权限记录")
    print("   - 删除后，get_permission_level('product')会在line 208返回'system'")
    print("   - DevProduct过滤逻辑会进入system级别分支，返回所有数据")
    print()
    
    print("方案2：修正个人权限记录的permission_level")
    print("   SQL:")
    print("   ```sql")
    print("   UPDATE permissions ")
    print("   SET permission_level = 'system' ")
    print("   WHERE user_id = 5 AND module = 'product';")
    print("   ```")
    print()
    print("   理由：")
    print("   - 保留权限记录但修正级别为system")
    print("   - 但不推荐，因为admin不应该有个人权限覆盖")
    print()
    
    print("方案3：修改代码逻辑（治本）")
    print("   位置：app/utils/access_control.py:459-509")
    print()
    print("   修改前：")
    print("   ```python")
    print("   if model_class.__name__ == 'DevProduct':")
    print("       if not user.has_permission('product', 'view'):")
    print("           return model_class.query.filter(False)")
    print("       permission_level = user.get_permission_level('product')")
    print("   ```")
    print()
    print("   修改后：")
    print("   ```python")
    print("   if model_class.__name__ == 'DevProduct':")
    print("       # admin用户直接返回所有数据，与其他模型保持一致")
    print("       if user.role == 'admin':")
    print("           return model_class.query.filter(*special_filters)")
    print("       ")
    print("       if not user.has_permission('product', 'view'):")
    print("           return model_class.query.filter(False)")
    print("       permission_level = user.get_permission_level('product')")
    print("   ```")
    print()
    print("   理由：")
    print("   - 确保DevProduct与其他模型的admin处理逻辑一致")
    print("   - 防止get_permission_level()被个人权限记录影响")
    print("   - 治标治本，避免未来类似问题")
    print()
    
    print("=" * 80)
    print("✅ 推荐执行步骤")
    print("=" * 80)
    print()
    print("1. 立即修复：删除错误的个人权限记录")
    print("   psql -d pma_local -c \"DELETE FROM permissions WHERE user_id = 5 AND module IN ('product', 'inventory');\"")
    print()
    print("2. 代码修复：添加admin检查到DevProduct特殊处理")
    print("   编辑：app/utils/access_control.py")
    print("   在line 459后添加admin检查")
    print()
    print("3. 验证修复：刷新研发产品列表页面")
    print("   应该能看到所有12条记录")
    print()
    
    print("=" * 80)
    print("📊 数据验证")
    print("=" * 80)
    print()
    print("修复前（personal权限级别）：")
    print("  - admin只能看到owner_id=5的10条记录")
    print("  - 看不到owner_id=10的2条记录")
    print()
    print("修复后（system权限级别）：")
    print("  - admin可以看到所有12条记录")
    print("  - 包括不同owner_id的所有数据")
    print()

if __name__ == '__main__':
    main()
