"""add updated_at to user

Revision ID: 012867901048
Revises: 2dea09543951
Create Date: 2025-05-13 12:37:01.168073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012867901048'
down_revision = '2dea09543951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_affiliations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    op.create_table('data_affiliations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='data_affiliations_owner_id_fkey'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name='data_affiliations_viewer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='data_affiliations_pkey'),
    sa.UniqueConstraint('owner_id', 'viewer_id', name='uix_data_owner_viewer')
    )
    # ### end Alembic commands ###
