
"""Add project customer association table

Revision ID: 06dd883f89fa
Revises: e75c868b86a3
Create Date: 2025-08-09 00:25:18.492498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dd883f89fa'
down_revision = 'e75c868b86a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('idx_companies_share_enabled')

    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='发票实际货币类型',
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.alter_column('invoice_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=False,
               comment=None,
               existing_comment='发票原始金额（发票货币）',
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('current_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=False,
               comment=None,
               existing_comment='换算金额（报销单货币）',
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('exchange_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               nullable=False,
               comment=None,
               existing_comment='换算汇率（发票货币→报销单货币）',
               existing_server_default=sa.text('1.0000'))
        batch_op.drop_index('idx_expense_details_currency')
        batch_op.drop_index('idx_expense_details_expense_currency')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='报销单主货币，用于最终结算和统计',
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.drop_index('idx_expenses_currency')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'personal'::character varying"))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('share_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index('idx_projects_share_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_share_enabled', ['share_enabled'], unique=False)
        batch_op.alter_column('share_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'personal'::character varying"))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('idx_expenses_currency', ['currency'], unique=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               comment='报销单主货币，用于最终结算和统计',
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.create_index('idx_expense_details_expense_currency', ['expense_id', 'currency'], unique=False)
        batch_op.create_index('idx_expense_details_currency', ['currency'], unique=False)
        batch_op.alter_column('exchange_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               comment='换算汇率（发票货币→报销单货币）',
               existing_server_default=sa.text('1.0000'))
        batch_op.alter_column('current_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               comment='换算金额（报销单货币）',
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('invoice_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               comment='发票原始金额（发票货币）',
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               comment='发票实际货币类型',
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('idx_companies_share_enabled', ['share_enabled'], unique=False)

    # ### end Alembic commands ###