"""Add project_stage and project_type to Quotation model

Revision ID: 077564ea4534
Revises: 301b965533f7
Create Date: 2025-04-16 09:08:09.606728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077564ea4534'
down_revision = '301b965533f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('project_stage', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('project_type', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'quotations', ['quotation_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotations', type_='unique')
    op.drop_column('quotations', 'project_type')
    op.drop_column('quotations', 'project_stage')
    # ### end Alembic commands ###
