"""添加产品所有者字段

Revision ID: 0b6652a48f2d
Revises: 23cb607de6ab
Create Date: 2025-04-18 23:53:00.458366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6652a48f2d'
down_revision = '23cb607de6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_owner_id_users', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
