
"""移除报销单表的department_id字段

Revision ID: 11b403f33385
Revises: 540d7c0dfa3c
Create Date: 2025-07-30 12:27:58.129481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b403f33385'
down_revision = '540d7c0dfa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('expenses_department_id_fkey', type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('expenses_department_id_fkey', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###