
"""Add content_filters field to role_permissions

Revision ID: 13bcdbbb799a
Revises: 27da792c7f12
Create Date: 2025-10-15 18:06:31.724399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bcdbbb799a'
down_revision = '27da792c7f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('content_filters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permissions', 'content_filters')
    # ### end Alembic commands ###