
"""添加绩效目标合格值字段

Revision ID: 1df903b77b75
Revises: 74974c79fe82
Create Date: 2025-08-01 08:13:52.764327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df903b77b75'
down_revision = '74974c79fe82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查字段是否存在，避免重复添加
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('performance_targets')]
    
    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        if 'implant_rate' not in columns:
            batch_op.add_column(sa.Column('implant_rate', sa.Integer(), nullable=True, default=0, comment='植入合格值'))
        if 'sales_rate' not in columns:
            batch_op.add_column(sa.Column('sales_rate', sa.Integer(), nullable=True, default=0, comment='销售合格值'))
        if 'customers_rate' not in columns:
            batch_op.add_column(sa.Column('customers_rate', sa.Integer(), nullable=True, default=0, comment='客户合格值'))
        if 'projects_rate' not in columns:
            batch_op.add_column(sa.Column('projects_rate', sa.Integer(), nullable=True, default=0, comment='项目合格值'))
    
    # 为现有记录设置默认值（无论字段是否新添加）
    op.execute("UPDATE performance_targets SET implant_rate = 0 WHERE implant_rate IS NULL")
    op.execute("UPDATE performance_targets SET sales_rate = 0 WHERE sales_rate IS NULL")
    op.execute("UPDATE performance_targets SET customers_rate = 0 WHERE customers_rate IS NULL")
    op.execute("UPDATE performance_targets SET projects_rate = 0 WHERE projects_rate IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        batch_op.drop_column('projects_rate')
        batch_op.drop_column('customers_rate')
        batch_op.drop_column('sales_rate')
        batch_op.drop_column('implant_rate')
    # ### end Alembic commands ###