"""add_company_sharing_fields

Revision ID: 2a8d58e077f8
Revises: 012867901048
Create Date: 2025-05-15 07:31:09.164412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8d58e077f8'
down_revision = '012867901048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_users', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('share_contacts', sa.Boolean(), nullable=True))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('override_share', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shared_disabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('shared_disabled')
        batch_op.drop_column('override_share')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('share_contacts')
        batch_op.drop_column('shared_with_users')

    # ### end Alembic commands ###
