"""Add action_ply

Revision ID: 2dea09543951
Revises: e29e27c7aa89
Create Date: 2025-05-11 21:21:44.070840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dea09543951'
down_revision = 'e29e27c7aa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_replies')
    with op.batch_alter_table('project_stage_history', schema=None) as batch_op:
        batch_op.drop_index('ix_project_stage_history_user_id')
        batch_op.drop_constraint('project_stage_history_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('project_stage_history_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_index('ix_project_stage_history_user_id', ['user_id'], unique=False)

    op.create_table('action_replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_reply_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='action_replies_action_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='action_replies_owner_id_fkey'),
    sa.ForeignKeyConstraint(['parent_reply_id'], ['action_replies.id'], name='action_replies_parent_reply_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='action_replies_pkey')
    )
    # ### end Alembic commands ###
