"""Add quotation_number field

Revision ID: 301b965533f7
Revises: ff77a5da4199
Create Date: 2025-04-15 23:48:07.404934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301b965533f7'
down_revision = 'ff77a5da4199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('quotation_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'quotation_number')
    # ### end Alembic commands ###
