"""Add owner_id to Action model

Revision ID: 30cab2a4db43
Revises: f5e98984140d
Create Date: 2025-04-18 23:23:36.624865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cab2a4db43'
down_revision = 'f5e98984140d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_actions_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_companies_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('report_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_unique_constraint('uq_projects_authorization_code', ['authorization_code'])

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('uq_quotations_quotation_number', ['quotation_number'])
        batch_op.drop_column('quotation_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint('uq_quotations_quotation_number', type_='unique')
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quotation_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_projects_authorization_code', type_='unique')
        batch_op.alter_column('report_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_owner_id_users', type_='foreignkey')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_actions_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
