
"""Add language_preference to User model

Revision ID: 38b3e335f251
Revises: 0432e8af4418
Create Date: 2025-06-16 08:52:13.364593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b3e335f251'
down_revision = '0432e8af4418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_orders', schema=None) as batch_op:
        batch_op.alter_column('is_direct_contract',
               existing_type=sa.BOOLEAN(),
               comment='厂商直签',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_factory_pickup',
               existing_type=sa.BOOLEAN(),
               comment='厂家提货',
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('project_scoring_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_scoring_record_with_user', type_='unique')
        batch_op.create_unique_constraint('uq_scoring_record', ['project_id', 'category', 'field_name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_preference', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language_preference')

    with op.batch_alter_table('project_scoring_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_scoring_record', type_='unique')
        batch_op.create_unique_constraint('uq_scoring_record_with_user', ['project_id', 'category', 'field_name', 'awarded_by'])

    with op.batch_alter_table('pricing_orders', schema=None) as batch_op:
        batch_op.alter_column('is_factory_pickup',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='厂家提货',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_direct_contract',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='厂商直签',
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###