"""Add image_path to Product model

Revision ID: 43d6fb80b38c
Revises: 7e3ee7e1bcc4
Create Date: 2025-04-19 15:59:38.686384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d6fb80b38c'
down_revision = '7e3ee7e1bcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_history')
    op.drop_table('workflow_log')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_projects_authorization_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_projects_authorization_code'), ['authorization_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_name'), ['project_name'], unique=False)
        batch_op.drop_column('quotation_customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_customer', sa.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_projects_project_name'))
        batch_op.drop_index(batch_op.f('ix_projects_authorization_code'))
        batch_op.create_unique_constraint('uq_projects_authorization_code', ['authorization_code'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    op.create_table('workflow_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=20), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('previous_status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('operator_id', sa.INTEGER(), nullable=False),
    sa.Column('operated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
