
"""重构报销单为主从表结构_添加报销明细表

Revision ID: 540d7c0dfa3c
Revises: d1c70d1043d7
Create Date: 2025-07-30 11:03:31.600977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540d7c0dfa3c'
down_revision = 'd1c70d1043d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 检查expense_details表是否已存在，如果不存在才创建
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if 'expense_details' not in inspector.get_table_names():
        # 创建报销明细表
        op.create_table('expense_details',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('expense_id', sa.Integer(), nullable=False),
            sa.Column('expense_date', sa.Date(), nullable=False),
            sa.Column('expense_category', sa.String(length=50), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('document_count', sa.Integer(), default=1),
            sa.Column('amount', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    # 修改报销主表结构
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.drop_constraint('expenses_action_id_fkey', type_='foreignkey')
        batch_op.drop_column('action_id')
        batch_op.drop_column('expense_category')
        batch_op.drop_column('amount')
        batch_op.drop_column('expense_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 恢复报销主表结构
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expense_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('expenses_action_id_fkey', 'actions', ['action_id'], ['id'])
        batch_op.drop_column('total_amount')
    
    # 删除报销明细表
    op.drop_table('expense_details')

    # ### end Alembic commands ###