
"""添加报销明细发票图片字段

Revision ID: 5b132cd64c70
Revises: 1df903b77b75
Create Date: 2025-08-03 16:20:28.363449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b132cd64c70'
down_revision = '1df903b77b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加发票图片字段到 expense_details 表
    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_images', sa.Text(), nullable=True, comment='发票图片JSON数据'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除发票图片字段
    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.drop_column('invoice_images')
    # ### end Alembic commands ###