
"""添加植入总额字段 implanted_total_amount 到 quotations 表

Revision ID: 69da2a6b4ac1
Revises: 5055ec5e2171
Create Date: 2025-06-05 09:52:43.399860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69da2a6b4ac1'
down_revision = '5055ec5e2171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_details', schema=None) as batch_op:
        batch_op.alter_column('implant_subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='植入小计：当产品品牌是和源通信时，零售价格 * 产品数量的值',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.drop_index('idx_quotation_details_implant_subtotal')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('implant_total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='植入总额合计：该报价单产品明细下所有植入小计值的合计',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.drop_index('idx_quotations_implant_total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('idx_quotations_implant_total_amount', ['implant_total_amount'], unique=False)
        batch_op.alter_column('implant_total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               comment='植入总额合计：该报价单产品明细下所有植入小计值的合计',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('quotation_details', schema=None) as batch_op:
        batch_op.create_index('idx_quotation_details_implant_subtotal', ['implant_subtotal'], unique=False)
        batch_op.alter_column('implant_subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               comment='植入小计：当产品品牌是和源通信时，零售价格 * 产品数量的值',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))

    # ### end Alembic commands ###