"""add role_permissions table

Revision ID: 6fe0f5c85141
Revises: add_missing_region_column
Create Date: 2025-05-05 02:45:29.051374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe0f5c85141'
down_revision = 'add_missing_region_column'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('affiliations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_affiliations_owner_id_users',
            'users',
            ['owner_id'],
            ['id']
        )
        batch_op.create_foreign_key(None, 'users', ['viewer_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('data_affiliations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['viewer_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('dev_product_specs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dev_products', ['dev_product_id'], ['id'])

    with op.batch_alter_table('dev_products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product_subcategories', ['subcategory_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'product_regions', ['region_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_categories', ['category_id'], ['id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_module', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('product_code_field_options', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product_code_fields', ['field_id'], ['id'])

    with op.batch_alter_table('product_code_field_values', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product_code_field_options', ['option_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_code_fields', ['field_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_codes', ['product_code_id'], ['id'])

    with op.batch_alter_table('product_code_fields', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product_subcategories', ['subcategory_id'], ['id'])
        batch_op.drop_column('name_en')

    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product_categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_subcategories', ['subcategory_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('product_subcategories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product_categories', ['category_id'], ['id'])
        batch_op.drop_column('position')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('quotation_details', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quotations', ['quotation_id'], ['id'])

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quotation_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('product_subcategories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('product_code_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('product_code_field_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('product_code_field_options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('unique_user_module', ['user_id', 'module'])

    with op.batch_alter_table('dev_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('dev_product_specs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('data_affiliations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('affiliations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_affiliations_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
