
"""添加行动记录共享字段

Revision ID: 74974c79fe82
Revises: 54e38919da4f
Create Date: 2025-08-01 02:29:20.590178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74974c79fe82'
down_revision = '54e38919da4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=True))
    
    # 为现有记录设置默认值为True（共享）
    op.execute("UPDATE actions SET is_shared = TRUE WHERE is_shared IS NULL")
    
    # 设置字段为不可空
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('is_shared', nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('share_related_projects',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('share_related_projects',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###