"""Add DataAffiliation model for user data affiliations

Revision ID: 768017ec056f
Revises: 96697e6742f3
Create Date: 2025-04-18 19:07:11.503605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768017ec056f'
down_revision = '96697e6742f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create DataAffiliation table
    op.create_table('data_affiliations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('viewer_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('owner_id', 'viewer_id', name='uix_data_owner_viewer')
    )
    
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('report_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['authorization_code'])

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['quotation_number'])
        batch_op.drop_column('quotation_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop DataAffiliation table
    op.drop_table('data_affiliations')
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quotation_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('report_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
