"""add position field to ProductCodeFieldOption model

Revision ID: 7dc4a4210ad4
Revises: 99cdaec46176
Create Date: 2025-04-24 07:40:46.873127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc4a4210ad4'
down_revision = '99cdaec46176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_code_field_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_code_field_options', schema=None) as batch_op:
        batch_op.drop_column('position')
    # ### end Alembic commands ###
