"""Add authorization_status and feedback to Project model

Revision ID: 7e3ee7e1bcc4
Revises: 0b6652a48f2d
Create Date: 2025-04-19 09:40:15.177635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3ee7e1bcc4'
down_revision = '0b6652a48f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorization_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('authorization_status')

    # ### end Alembic commands ###
