
"""initial revision for deployment

Revision ID: 805c8f258a33
Revises: 
Create Date: 2025-05-22 16:55:32.475175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '805c8f258a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint('actions_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('approval_process_template', schema=None) as batch_op:
        batch_op.alter_column('required_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='发起审批时必填字段列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('approval_record', schema=None) as batch_op:
        batch_op.alter_column('instance_id',
               existing_type=sa.INTEGER(),
               comment='审批流程实例',
               existing_nullable=False)
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               comment='流程步骤ID',
               existing_nullable=False)
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               comment='审批人ID',
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               comment='同意/拒绝',
               existing_nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               comment='审批意见',
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='审批时间',
               existing_nullable=True)
        batch_op.drop_constraint('fk_approval_record_instance_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'approval_instance', ['instance_id'], ['id'])

    with op.batch_alter_table('approval_step', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=50),
               comment='步骤动作类型，如 authorization',
               existing_nullable=True)
        batch_op.alter_column('action_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='动作参数，JSON格式',
               existing_nullable=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_constraint('project_members_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('project_stage_history', schema=None) as batch_op:
        batch_op.drop_constraint('project_stage_history_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint('quotations_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quotations_project_id_fkey', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('project_stage_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_stage_history_project_id_fkey', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_members_project_id_fkey', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('approval_step', schema=None) as batch_op:
        batch_op.alter_column('action_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='动作参数，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='步骤动作类型，如 authorization',
               existing_nullable=True)

    with op.batch_alter_table('approval_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_approval_record_instance_id', 'approval_instance', ['instance_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='审批时间',
               existing_nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='审批意见',
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='同意/拒绝',
               existing_nullable=False)
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='审批人ID',
               existing_nullable=False)
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='流程步骤ID',
               existing_nullable=False)
        batch_op.alter_column('instance_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='审批流程实例',
               existing_nullable=False)

    with op.batch_alter_table('approval_process_template', schema=None) as batch_op:
        batch_op.alter_column('required_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='发起审批时必填字段列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('actions_project_id_fkey', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###