"""add user_id to project_stage_history

Revision ID: 88818cc52fa3
Revises: 07bd9afe4c03
Create Date: 2025-05-10 12:26:48.155339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88818cc52fa3'
down_revision = '07bd9afe4c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('change_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('change_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('change_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_index('ix_project_stage_history_changed_at')
        batch_op.create_index(batch_op.f('ix_project_stage_history_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('project_stage_history_operator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('operator_id')
        batch_op.drop_column('changed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('operator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_stage_history_operator_id_fkey', 'users', ['operator_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_project_stage_history_user_id'))
        batch_op.create_index('ix_project_stage_history_changed_at', ['changed_at'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')
        batch_op.drop_column('remarks')
        batch_op.drop_column('change_year')
        batch_op.drop_column('change_month')
        batch_op.drop_column('change_week')
        batch_op.drop_column('change_date')

    # ### end Alembic commands ###
