"""Add content_filters field to permissions table

Revision ID: 8cceb1f66801
Revises: 13bcdbbb799a
Create Date: 2025-10-16 22:26:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cceb1f66801'
down_revision = '13bcdbbb799a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('content_filters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'content_filters')
    # ### end Alembic commands ###
