"""Add data ownership and affiliation models with batch support

Revision ID: 96697e6742f3
Revises: 077564ea4534
Create Date: 2025-04-18 16:55:30.390548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96697e6742f3'
down_revision = '077564ea4534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_companies_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_contacts_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_projects_authorization_code', ['authorization_code'])
        batch_op.create_foreign_key('fk_projects_owner_id_users', 'users', ['owner_id'], ['id'])
        batch_op.alter_column('report_time',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.drop_column('quotation_date')
        batch_op.create_unique_constraint('uq_quotations_quotation_number', ['quotation_number'])
        batch_op.create_foreign_key('fk_quotations_owner_id_users', 'users', ['owner_id'], ['id'])
        batch_op.alter_column('quotation_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_affiliations_owner_id_users'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name='fk_affiliations_viewer_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'viewer_id', name='uix_owner_viewer')
    )
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    op.drop_table('affiliations')
    
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quotation_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_constraint('fk_quotations_owner_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_quotations_quotation_number', type_='unique')
        batch_op.add_column(sa.Column('quotation_date', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('report_time',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_constraint('fk_projects_owner_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_projects_authorization_code', type_='unique')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###
