"""Add product subcategory structure

Revision ID: 99cdaec46176
Revises: dad11f26e346
Create Date: 2025-04-23 00:12:03.214127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cdaec46176'
down_revision = 'dad11f26e346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_code_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_subcategories', ['subcategory_id'], ['id'])
        batch_op.drop_column('category_id')

    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'product_subcategories', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    with op.batch_alter_table('product_code_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_categories', ['category_id'], ['id'])
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
