"""expand password_hash length to 256

Revision ID: 9af1b99fb2fb
Revises: 6fe0f5c85141
Create Date: 2025-05-05 22:12:58.062969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af1b99fb2fb'
down_revision = '6fe0f5c85141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_code_fields', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    with op.batch_alter_table('product_subcategories', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('product_subcategories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('product_code_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
