
"""添加报销单和明细记录草稿状态

Revision ID: 9bbc21d823f8
Revises: 11b403f33385
Create Date: 2025-07-30 12:48:54.164736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbc21d823f8'
down_revision = '11b403f33385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空的status字段
    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
    
    # 为现有记录设置默认状态为'draft'
    op.execute("UPDATE expense_details SET status = 'draft' WHERE status IS NULL")
    
    # 将字段改为非空
    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)
    
    # 更新现有报销单状态为'draft'（如果它们当前是'pending'）
    op.execute("UPDATE expenses SET status = 'draft' WHERE status = 'pending'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###