
"""添加报销单联系人字段

Revision ID: afb642ad7071
Revises: 5b132cd64c70
Create Date: 2025-08-03 17:07:55.217551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb642ad7071'
down_revision = '5b132cd64c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.alter_column('invoice_images',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='发票图片JSON数据',
               existing_nullable=True)

    # 分步骤添加联系人字段，处理现有数据
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        # 第一步：添加可空的contact_id字段
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
    
    # 第二步：为现有报销单设置默认联系人（使用客户的第一个联系人）
    connection = op.get_bind()
    try:
        # 首先为没有联系人的公司创建一个默认联系人
        create_default_contact_sql = """
        INSERT INTO contacts (company_id, name, created_at, updated_at)
        SELECT DISTINCT e.customer_id, '默认联系人', NOW(), NOW()
        FROM expenses e 
        WHERE e.customer_id NOT IN (
            SELECT DISTINCT company_id FROM contacts WHERE company_id IS NOT NULL
        )
        """
        connection.execute(sa.text(create_default_contact_sql))
        
        # 然后更新现有记录，为每个客户找到第一个联系人
        update_sql = """
        UPDATE expenses 
        SET contact_id = (
            SELECT c.id 
            FROM contacts c 
            WHERE c.company_id = expenses.customer_id 
            ORDER BY c.id 
            LIMIT 1
        ) 
        WHERE contact_id IS NULL 
        AND customer_id IS NOT NULL
        """
        connection.execute(sa.text(update_sql))
    except Exception as e:
        print(f"Warning: Failed to update existing expense records with contact_id: {e}")
    
    # 第三步：将字段改为非空，并添加外键约束
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('contact_id', nullable=False)
        batch_op.create_foreign_key('fk_expenses_contact_id', 'contacts', ['contact_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_contact_id', type_='foreignkey')
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('expense_details', schema=None) as batch_op:
        batch_op.alter_column('invoice_images',
               existing_type=sa.TEXT(),
               comment='发票图片JSON数据',
               existing_nullable=True)

    # ### end Alembic commands ###