
"""添加项目status字段支持订单审批系统

Revision ID: b2d5b2180d45
Revises: 818231a27ec4
Create Date: 2025-08-17 21:23:07.624437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2d5b2180d45'
down_revision = '818231a27ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_step', schema=None) as batch_op:
        batch_op.alter_column('step_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='步骤类型：normal(常规) 或 branch(分支)',
               existing_server_default=sa.text("'normal'::character varying"))
        batch_op.alter_column('branch_condition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='分支条件配置',
               existing_nullable=True)
        batch_op.alter_column('parent_step_id',
               existing_type=sa.INTEGER(),
               comment='[废弃] 上级步骤ID，用于并行分支',
               existing_nullable=True)
        batch_op.alter_column('is_parallel',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='[废弃] 是否为并行分支',
               existing_server_default=sa.text('false'))
        batch_op.alter_column('branch_group_id',
               existing_type=sa.VARCHAR(length=50),
               comment='[废弃] 分支组ID，用于标识同一组并行分支',
               existing_nullable=True)
        batch_op.alter_column('branch_level',
               existing_type=sa.INTEGER(),
               comment='[废弃] 分支层级，0为主流程，1为一级分支，以此类推',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('branch_path',
               existing_type=sa.VARCHAR(length=100),
               comment="[废弃] 分支路径，如 'true.false.true' 表示分支选择路径",
               existing_nullable=True)
        batch_op.alter_column('merge_step_id',
               existing_type=sa.INTEGER(),
               comment='[废弃] 分支合并步骤ID',
               existing_nullable=True)
        batch_op.drop_constraint('fk_approval_step_parent_step', type_='foreignkey')
        batch_op.create_foreign_key(None, 'approval_step', ['parent_step_id'], ['id'])

    with op.batch_alter_table('project_customer_associations', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建此客户关联的用户ID',
               existing_nullable=True)

    # 添加status字段 - 分步骤执行以避免NOT NULL约束错误
    with op.batch_alter_table('projects', schema=None) as batch_op:
        # 第一步：添加可空字段
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
    
    # 第二步：更新现有记录的status值为'draft'
    op.execute("UPDATE projects SET status = 'draft' WHERE status IS NULL")
    
    # 第三步：设置字段为NOT NULL
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('project_customer_associations', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               comment='创建此客户关联的用户ID',
               existing_nullable=True)

    with op.batch_alter_table('approval_step', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_approval_step_parent_step', 'approval_step', ['parent_step_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('merge_step_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='[废弃] 分支合并步骤ID',
               existing_nullable=True)
        batch_op.alter_column('branch_path',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="[废弃] 分支路径，如 'true.false.true' 表示分支选择路径",
               existing_nullable=True)
        batch_op.alter_column('branch_level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='[废弃] 分支层级，0为主流程，1为一级分支，以此类推',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('branch_group_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='[废弃] 分支组ID，用于标识同一组并行分支',
               existing_nullable=True)
        batch_op.alter_column('is_parallel',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='[废弃] 是否为并行分支',
               existing_server_default=sa.text('false'))
        batch_op.alter_column('parent_step_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='[废弃] 上级步骤ID，用于并行分支',
               existing_nullable=True)
        batch_op.alter_column('branch_condition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='分支条件配置',
               existing_nullable=True)
        batch_op.alter_column('step_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='步骤类型：normal(常规) 或 branch(分支)',
               existing_server_default=sa.text("'normal'::character varying"))

    # ### end Alembic commands ###