"""Add quotation_customer field to Project model

Revision ID: b2e3a594f642
Revises: f69d654c14da
Create Date: 2025-04-19 22:52:56.630391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e3a594f642'
down_revision = 'f69d654c14da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_customer', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('quotation_customer')

    # ### end Alembic commands ###
