
"""sync_local_to_sp8d_20250801_004047

Revision ID: b891f72a8dcb
Revises: 9bbc21d823f8
Create Date: 2025-08-01 00:40:48.764692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b891f72a8dcb'
down_revision = '9bbc21d823f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('is_locked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='锁定状态，草稿状态下默认未锁定',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index('idx_expenses_is_locked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('idx_expenses_is_locked', ['is_locked'], unique=False)
        batch_op.alter_column('is_locked',
               existing_type=sa.BOOLEAN(),
               comment='锁定状态，草稿状态下默认未锁定',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###