
"""add_expense_and_department_tables

Revision ID: d1c70d1043d7
Revises: af7e0e1e6e51
Create Date: 2025-07-30 08:18:06.110755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1c70d1043d7'
down_revision = 'af7e0e1e6e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_process_template', schema=None) as batch_op:
        batch_op.drop_column('visual_data')

    with op.batch_alter_table('approval_record', schema=None) as batch_op:
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               comment='流程步骤ID（模板快照时可为NULL）',
               existing_comment='流程步骤ID',
               existing_nullable=True)

    with op.batch_alter_table('approval_step', schema=None) as batch_op:
        batch_op.alter_column('approver_type',
               existing_type=sa.VARCHAR(length=20),
               comment='审批人类型：user(固定用户) 或 auto(自动选择)',
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment='步骤描述',
               existing_nullable=True)
        batch_op.drop_column('skip_conditions')
        batch_op.drop_column('branch_on_approve')
        batch_op.drop_column('branch_on_reject')
        batch_op.drop_column('condition_config')
        batch_op.drop_column('is_conditional')
        batch_op.drop_column('condition_type')

    with op.batch_alter_table('dev_products', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('dictionaries', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='详细地址（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='邮政编码（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='企业电话（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('fax',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='传真（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='企业邮箱（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='网站地址（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Logo的Base64内容（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_filename',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Logo原始文件名（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Logo文件类型（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Logo文件大小字节（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email_signature_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='邮件签名图片的Base64内容（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email_signature_filename',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='邮件签名原始文件名（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email_signature_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='邮件签名文件类型（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email_signature_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='邮件签名文件大小字节（仅对company类型有效）',
               existing_nullable=True)
        # 这些索引在SP8D中不存在，直接跳过删除操作
        # batch_op.drop_index('idx_dictionaries_company_email', postgresql_where="((type)::text = 'company'::text)")
        # batch_op.drop_index('idx_dictionaries_company_logo', postgresql_where='(logo_content IS NOT NULL)')
        # batch_op.drop_index('idx_dictionaries_company_phone', postgresql_where="((type)::text = 'company'::text)")

    with op.batch_alter_table('five_star_project_baselines', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('baseline_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='基线年份',
               existing_nullable=False)
        batch_op.alter_column('baseline_month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='基线月份',
               existing_nullable=False)
        batch_op.alter_column('baseline_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='基线五星项目数量',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.drop_constraint('unique_baseline_user', type_='unique')

    with op.batch_alter_table('performance_statistics', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年份',
               existing_nullable=False)
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='月份',
               existing_nullable=False)
        batch_op.alter_column('implant_amount_actual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               comment=None,
               existing_comment='植入额实际完成',
               existing_nullable=True)
        batch_op.alter_column('sales_amount_actual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               comment=None,
               existing_comment='销售额实际完成',
               existing_nullable=True)
        batch_op.alter_column('new_customers_actual',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='新增客户数实际完成',
               existing_nullable=True)
        batch_op.alter_column('new_projects_actual',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='新增项目数实际完成',
               existing_nullable=True)
        batch_op.alter_column('five_star_projects_actual',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='五星项目增量实际完成',
               existing_nullable=True)
        batch_op.alter_column('industry_statistics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='行业维度统计数据',
               existing_nullable=True)
        batch_op.alter_column('calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='统计计算时间',
               existing_nullable=True)
        batch_op.drop_constraint('unique_statistics_user_year_month', type_='unique')
        batch_op.create_unique_constraint('uq_performance_stats_user_year_month', ['user_id', 'year', 'month'])

    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='年份',
               existing_nullable=False)
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='月份',
               existing_nullable=False)
        batch_op.alter_column('implant_amount_target',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               comment=None,
               existing_comment='植入额目标',
               existing_nullable=True)
        batch_op.alter_column('sales_amount_target',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               comment=None,
               existing_comment='销售额目标',
               existing_nullable=True)
        batch_op.alter_column('new_customers_target',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='新增客户数目标',
               existing_nullable=True)
        batch_op.alter_column('new_projects_target',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='新增项目数目标',
               existing_nullable=True)
        batch_op.alter_column('five_star_projects_target',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='五星项目增量目标',
               existing_nullable=True)
        batch_op.alter_column('display_currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='用户选择的展示货币',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='创建人')
        batch_op.drop_constraint('unique_user_year_month', type_='unique')
        batch_op.create_unique_constraint('uq_performance_target_user_year_month', ['user_id', 'year', 'month'])

    with op.batch_alter_table('pricing_order_details', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               comment='货币类型',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('pricing_orders', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               comment='货币类型',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_current_stage')
        batch_op.drop_index('idx_projects_owner_id')
        batch_op.drop_index('idx_projects_project_type')
        batch_op.drop_index('idx_projects_type_stage')
        batch_op.drop_index('idx_projects_vendor_sales_manager')

    with op.batch_alter_table('quotation_details', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('original_market_price')
        batch_op.drop_column('converted_market_price')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.drop_index('idx_quotations_amount')
        batch_op.drop_index('idx_quotations_created_at')
        batch_op.drop_index('idx_quotations_owner_id')
        batch_op.drop_index('idx_quotations_project_id')
        batch_op.drop_index('idx_quotations_project_owner')
        batch_op.drop_index('idx_quotations_updated_at')
        batch_op.drop_column('original_currency')
        batch_op.drop_column('exchange_rate')

    with op.batch_alter_table('settlement_order_details', schema=None) as batch_op:
        batch_op.alter_column('settlement_status',
               existing_type=sa.VARCHAR(length=20),
               comment='结算状态: draft, pending, settled',
               existing_comment='结算状态: pending, completed',
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               comment='货币类型',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('settlement_orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='结算单审批状态',
               existing_comment='结算单状态',
               existing_nullable=True)

    with op.batch_alter_table('temp_products', schema=None) as batch_op:
        batch_op.alter_column('reference_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='参考价格（保存时的单价）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_products', schema=None) as batch_op:
        batch_op.alter_column('reference_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='参考价格（保存时的单价）',
               existing_nullable=True)

    with op.batch_alter_table('settlement_orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='结算单状态',
               existing_comment='结算单审批状态',
               existing_nullable=True)

    with op.batch_alter_table('settlement_order_details', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='货币类型',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.alter_column('settlement_status',
               existing_type=sa.VARCHAR(length=20),
               comment='结算状态: pending, completed',
               existing_comment='结算状态: draft, pending, settled',
               existing_nullable=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=6), server_default=sa.text('1.000000'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
        batch_op.create_index('idx_quotations_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_quotations_project_owner', ['project_id', 'owner_id'], unique=False)
        batch_op.create_index('idx_quotations_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_quotations_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('idx_quotations_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_quotations_amount', ['amount'], unique=False)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('quotation_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converted_market_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_market_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_vendor_sales_manager', ['vendor_sales_manager_id'], unique=False)
        batch_op.create_index('idx_projects_type_stage', ['project_type', 'current_stage'], unique=False)
        batch_op.create_index('idx_projects_project_type', ['project_type'], unique=False)
        batch_op.create_index('idx_projects_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('idx_projects_current_stage', ['current_stage'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('pricing_orders', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='货币类型',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('pricing_order_details', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='货币类型',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('performance_targets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_performance_target_user_year_month', type_='unique')
        batch_op.create_unique_constraint('unique_user_year_month', ['user_id', 'year', 'month'])
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='创建人')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('display_currency',
               existing_type=sa.VARCHAR(length=10),
               comment='用户选择的展示货币',
               existing_nullable=True)
        batch_op.alter_column('five_star_projects_target',
               existing_type=sa.INTEGER(),
               comment='五星项目增量目标',
               existing_nullable=True)
        batch_op.alter_column('new_projects_target',
               existing_type=sa.INTEGER(),
               comment='新增项目数目标',
               existing_nullable=True)
        batch_op.alter_column('new_customers_target',
               existing_type=sa.INTEGER(),
               comment='新增客户数目标',
               existing_nullable=True)
        batch_op.alter_column('sales_amount_target',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='销售额目标',
               existing_nullable=True)
        batch_op.alter_column('implant_amount_target',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='植入额目标',
               existing_nullable=True)
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               comment='月份',
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               comment='年份',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('performance_statistics', schema=None) as batch_op:
        batch_op.drop_constraint('uq_performance_stats_user_year_month', type_='unique')
        batch_op.create_unique_constraint('unique_statistics_user_year_month', ['user_id', 'year', 'month'])
        batch_op.alter_column('calculated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='统计计算时间',
               existing_nullable=True)
        batch_op.alter_column('industry_statistics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='行业维度统计数据',
               existing_nullable=True)
        batch_op.alter_column('five_star_projects_actual',
               existing_type=sa.INTEGER(),
               comment='五星项目增量实际完成',
               existing_nullable=True)
        batch_op.alter_column('new_projects_actual',
               existing_type=sa.INTEGER(),
               comment='新增项目数实际完成',
               existing_nullable=True)
        batch_op.alter_column('new_customers_actual',
               existing_type=sa.INTEGER(),
               comment='新增客户数实际完成',
               existing_nullable=True)
        batch_op.alter_column('sales_amount_actual',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='销售额实际完成',
               existing_nullable=True)
        batch_op.alter_column('implant_amount_actual',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='植入额实际完成',
               existing_nullable=True)
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               comment='月份',
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               comment='年份',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('five_star_project_baselines', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_baseline_user', ['user_id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('baseline_count',
               existing_type=sa.INTEGER(),
               comment='基线五星项目数量',
               existing_nullable=True)
        batch_op.alter_column('baseline_month',
               existing_type=sa.INTEGER(),
               comment='基线月份',
               existing_nullable=False)
        batch_op.alter_column('baseline_year',
               existing_type=sa.INTEGER(),
               comment='基线年份',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)

    with op.batch_alter_table('dictionaries', schema=None) as batch_op:
        batch_op.create_index('idx_dictionaries_company_phone', ['type', 'phone'], unique=False, postgresql_where="((type)::text = 'company'::text)")
        batch_op.create_index('idx_dictionaries_company_logo', ['type'], unique=False, postgresql_where='(logo_content IS NOT NULL)')
        batch_op.create_index('idx_dictionaries_company_email', ['type', 'email'], unique=False, postgresql_where="((type)::text = 'company'::text)")
        batch_op.alter_column('email_signature_size',
               existing_type=sa.INTEGER(),
               comment='邮件签名文件大小字节（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email_signature_type',
               existing_type=sa.VARCHAR(length=50),
               comment='邮件签名文件类型（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email_signature_filename',
               existing_type=sa.VARCHAR(length=100),
               comment='邮件签名原始文件名（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email_signature_content',
               existing_type=sa.TEXT(),
               comment='邮件签名图片的Base64内容（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_size',
               existing_type=sa.INTEGER(),
               comment='Logo文件大小字节（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Logo文件类型（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_filename',
               existing_type=sa.VARCHAR(length=100),
               comment='Logo原始文件名（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('logo_content',
               existing_type=sa.TEXT(),
               comment='Logo的Base64内容（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=200),
               comment='网站地址（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               comment='企业邮箱（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('fax',
               existing_type=sa.VARCHAR(length=50),
               comment='传真（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               comment='企业电话（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment='邮政编码（仅对company类型有效）',
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               comment='详细地址（仅对company类型有效）',
               existing_nullable=True)

    with op.batch_alter_table('dev_products', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('approval_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_conditional', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('condition_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('branch_on_reject', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('branch_on_approve', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skip_conditions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='步骤描述',
               existing_nullable=True)
        batch_op.alter_column('approver_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='审批人类型：user(固定用户) 或 auto(自动选择)',
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))

    with op.batch_alter_table('approval_record', schema=None) as batch_op:
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               comment='流程步骤ID',
               existing_comment='流程步骤ID（模板快照时可为NULL）',
               existing_nullable=True)

    with op.batch_alter_table('approval_process_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visual_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###