"""remove_company_id_from_quotations

Revision ID: f69d654c14da
Revises: cc00d44c703f
Create Date: 2025-04-19 21:51:09.084582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69d654c14da'
down_revision = 'cc00d44c703f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_quotations_company_id_companies', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###
