
"""Add pdf_path field to products table

Revision ID: 669777b71041
Revises: 7dfcf037db65
Create Date: 2025-05-27 12:51:26.304776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669777b71041'
down_revision = '7dfcf037db65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###