
"""Add pdf_path field to dev_products table

Revision ID: 7dfcf037db65
Revises: product_analysis_2025
Create Date: 2025-05-27 12:43:10.402089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfcf037db65'
down_revision = 'product_analysis_2025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_products', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###